name: Twitter List Cron Job

on:
  schedule:
    # 15分間隔で実行（Vercel Cronと同じ）
    - cron: '*/15 * * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Cron Job
        run: |
          curl -X POST "${{ secrets.VERCEL_PRODUCTION_URL }}/api/cron/universal-executor" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -d '{}'